version: '3'

services:
    php-es:
        build: .
        working_dir: /var/www
        volumes:
            - ../../www:/var/www
    nginx-es:
        image: nginx:alpine
        ports:
            - 80:80
        working_dir: /var/www
        volumes:
            - ../../www:/var/www
            - ./site.conf:/etc/nginx/conf.d/default.conf 
    es:
        image: elasticsearch:6.5.4
        ports:
            - 9200:9200
        volumes:
            - ../../www:/var/www
    mysql-es:
        restart: always
        image: mysql:5.7
        user: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: elastic
            MYSQL_USER: elastic
            MYSQL_PASSWORD: elastic
        volumes:
            - ../mysqldata:/var/lib/mysql
