version: '3'

services:
    php-es:
        build: .
        volumes:
            - ../../www:/var/www
    nginx-es:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ../../www:/www
            - ./site.conf:/etc/nginx/conf.d/default.conf 
    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
        ports:
            - 9200:9200
        volumes:
            - ../../www:/www
    mysql-es:
        restart: always
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: elastic
            MYSQL_USER: elastic
            MYSQL_PASSWORD: elastic
        volumes:
            - ../mysqldata:/var/lib/mysql
